smsServices:
# ----------------
# TEST "SERVICE"
# - url: 'https://httpbin.org/post'
#   method: 'POST'
#   headers:
#     Content-Type: 'application/json'
#   body: '{"phone_number":"<num>"}'
#   okRes: 'origin'
#   delay: 5
# ----------------
- url: 'https://connect.vk.com/auth?app_id=7733222&v=0.0.2&redirect_uri=https%3A%2F%2Fyoula.ru%2Fmoskva&uuid=9dD6SybfGij7CNjdXrb6F&redirect_state=vk-connect-auth-redirect&app_settings=eyJ2a2NfYmVoYXZpb3IiOiJ3aXRob3V0X3Bob25lIiwic2VydmljZV9ncm91cHMiOnsiZnVsbF9hdXRoX3ZpYV92a2Nvbm5lY3QiOiJleHAifSwiZXh0ZXJuYWxfZGV2aWNlX2lkIjoiNjIxNGRlN2EzOGVhOSJ9'
  method: 'GET'
  body: 'phone=<num>'
  okRes: '"phone"'
  delay: 3

- url: 'https://youla.ru/web-api/auth/request_code'
  method: 'POST'
  body: 'phone=<num>'
  okRes: '"phone"'
  delay: 16

- url: 'https://apteka366.ru/login/register/sms/send'
  method: 'POST'
  body: 'phone=<num>'
  okRes: '"phone"'
  delay: 121

- url: 'https://366.ru/'
  method: 'POST'
  body: 'phone=<num>'
  okRes: '"phone"'
  delay: 127


- url: 'https://fundayshop.com/ru/ru/secured/myaccount/myclubcard/resultClubCard.jsp?type=sendConfirmCode&phoneNumber=+<num13>'
  method: 'GET'
  body: 'phone=<num>'
  okRes: '"phone"'
  delay: 135

- url: 'https://fundayshop.com/ru/ru/secured/myaccount/myclubcard/resultClubCard.jsp?type=sendConfirmCode&phoneNumber=+<num13>'
  method: 'GET'
  body: 'phone=<num>'
  okRes: 'result":"sendConfirmCode'
  delay: 50

- url: 'https://gorzdrav.org/login/register/sms/send'
  method: 'POST'
  body: 'phone=<num>'
  okRes: 'phone'
  delay: 94


- url: 'https://www.mvideo.ru/login'
  method: 'POST'
  body: 'phone=<num>'
  okRes: '"phone"'
  delay: 32


- url: 'https://passport.yandex.ru/auth?backpath=https%3A%2F%2Feda.yandex.ru%2Fmoscow%3FredirectFrom%3Dlegacy_host%26shippingType%3Ddelivery&origin=eats_desktop&retpath=https%3A%2F%2Feda.yandex.ru%2Fmoscow%3Fauth_from%3Dside_menu%26redirectFrom%3Dlegacy_host%26shippingType%3Ddelivery'
  method: 'POST'
  okRes: '"delay"'
  delay: 67




callServices:
- url: 'https://findclone.ru/register?phone=+<num>'
  method: 'GET'
  okRes: '"pin_size"'
  body: 'phone=<num>'
  okRes: '"phone"'
  delay: 61


- url: 'https://findclone.ru/register?phone=+<num>'
  method: 'GET'
  okRes: '"authorization__link"'
  body: 'phone=<num>'
  okRes: '"phone"'
  delay: 61
